export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_PRODUCTS_BY_TYPE = 'ADD_PRODUCTS_BY_TYPE';
export const PRODUCTS_BY_TYPE_FAILED = 'PRODUCTS_BY_TYPE_FAILED';